use crate::constants::CONFIG_EXTENSION;
use crate::error::{DeclarchError, Result};
use crate::utils::paths;
use std::fs;
use std::path::PathBuf;

/// Resolve module path from module name.
///
/// Examples:
/// - None → modules/others.kdl
/// - "base" → modules/base.kdl
/// - "linux/notes" → modules/linux/notes.kdl
pub(super) fn resolve_module_path(module: Option<&str>) -> Result<PathBuf> {
    let modules_dir = paths::modules_dir()?;

    let target_file = match module {
        Some(mod_name) => {
            let parts: Vec<&str> = mod_name.split('/').collect();

            let file_name = format!(
                "{}.{}",
                parts
                    .last()
                    .ok_or_else(|| DeclarchError::Other("Invalid module path".to_string()))?,
                CONFIG_EXTENSION
            );
            let dir_path = parts
                .iter()
                .take(parts.len() - 1)
                .fold(modules_dir, |acc, part| acc.join(part));

            if !dir_path.exists() {
                fs::create_dir_all(&dir_path).map_err(|e| {
                    DeclarchError::Other(format!("Failed to create directory: {}", e))
                })?;
            }

            dir_path.join(file_name)
        }
        None => modules_dir.join(format!("others.{}", CONFIG_EXTENSION)),
    };

    Ok(target_file)
}

pub(super) fn create_default_module(path: &PathBuf) -> Result<()> {
    let module_name = path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| DeclarchError::Other("Invalid module name".to_string()))?;

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| {
            DeclarchError::Other(format!("Failed to create module directory: {}", e))
        })?;
    }

    let default_content = format!(
        "// Declarch module: {}\n\
        // Generated by declarch install command\n\
        \n\
        pkg {{\n\
          // Add packages here\n\
        }}\n",
        module_name
    );

    fs::write(path, default_content)
        .map_err(|e| DeclarchError::Other(format!("Failed to create module: {}", e)))?;

    Ok(())
}
